## Information

```
Name: Linux/OSX Compatibility
Priority: High
Found in: 0.10.0
Fixed in: None
```

## Description
The PiOS does not seem to work for Linux and OSX because the default `os.altsep` being `None` which raises something
like this
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xcodz/.local/lib/python3.9/site-packages/pios/launchers/pios.py", line 23, in <module>
    operating_system = import_module(f"pios.installed_os.{Args.operating_system}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/xcodz/.local/lib/python3.9/site-packages/pios/installed_os/pios.py", line 9, in <module>
    "root": "{os.getcwd().replace(os.sep, os.altsep)}"
TypeError: replace() argument 2 must be str, not None
```

## Reproduction Steps

Requirements:
* Linux/OSX installed Laptop/PC/Virtual Machine

Steps:
* Install `pios==0.10.0`
* Run `python3 -m pios`
